### ISSUE TITLE
ocultar

### ISSUE THREAD

**Issue by Luis-Rodes** [Luis-Rodes/PracticasVue#1]
Buenas @pedroprieto voy un poco perdido al realizar el ponte a prueba de vue, el de ocultar las capas, le puedes dar un vistazo?
Funcionar funciona, pero no lo veo muy correcto.
Gracias.

**Comment by pedroprieto** [comment]
Buenas,

Está correcta. Podrías utilizar `v-else` junto con `v-if` para ocultar una capa cuando se muestre la otra. Y también, en los manejadores de eventos:
https://github.com/Luis-Rodes/PracticasVue/blob/dc9da74d4472b6da012e5dc77eccb22168e7dd6a/index.html#L28

Llamar a los métodos que tienes, `cerrarVista`, por ejemplo. Que sean esos métodos los que cambien el valor de la variable `vista` y que adicionalmente muestren el `alert` si quieres.

Un saludo y ánimo!

**Comment by Luis-Rodes** [comment]
Perdona la tardanza pero he vuelto a estar fuera por trabajo, lo intente y por eso cree los methos pero al final no me aclare mucho y vi esa opcion en la pagina de vuejs y lo hice, a ver si esta semana voy mas tranquilo de trabajo y me pongo mas a fondo, gracias pedro.
